### ISSUE TITLE
Skripta koja ispisuje slobodnu memoriju

### ISSUE THREAD

**Issue by neidiom** [Pohakontas98/linux#1]
* Napisati skriptu koja izlistava slobodnu memoriju s tim da treba posebno izlistati **total** memory, posebno **RAM** memory a posebno **SWAP** memory

**Comment by neidiom** [comment]
Za ovaj issue koristiti `free` komandu, pogledati tutorial u sljedecem primjeru

https://www.tecmint.com/check-memory-usage-in-linux/

**Comment by AdiPezer** [comment]
Zavrsio
